In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

columns = [
    "age", "workclass", "fnlwgt", "education", "education_num",
    "marital_status", "occupation", "relationship", "race", "sex",
    "capital_gain", "capital_loss", "hours_per_week",
    "native_country", "income"
]

df = pd.read_csv(
    r"C:\Users\Soham\Desktop\Adult Income Data Cleaning and EDA\Data\clean_income_data.csv",
    names=columns,
    skipinitialspace=True,
    skiprows=1
)

print(df.shape)
df.head(5)

(48842, 15)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,50K or Less
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,50K or Less
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,50K or Less
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,50K or Less
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,50K or Less

In [3]:
test = pd.read_csv(
    r"C:\Users\Soham\Desktop\Adult Income Data Cleaning and EDA\Data\clean_income_data.csv",
    names=columns,
    skipinitialspace=True,
    skiprows=1
)

test.shape

(48842, 15)

In [4]:
# df = pd.concat([data, test], ignore_index=True)

# df.shape

In [5]:
df.columns.duplicated().sum()

0

In [6]:
df.head(5)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,50K or Less
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,50K or Less
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,50K or Less
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,50K or Less
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,50K or Less

In [7]:
# convert all columns name into title case
df.columns=df.columns.str.title()
print("title",df.columns)

title Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education_Num',
       'Marital_Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital_Gain', 'Capital_Loss', 'Hours_Per_Week', 'Native_Country',
       'Income'],
      dtype='object')

In [8]:
df.head(2)

,Age,Workclass,Fnlwgt,Education,Education_Num,Marital_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_Per_Week,Native_Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,50K or Less
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,50K or Less

In [9]:
# Age column audit

print("Data type:", df['Age'].dtype)
print("-" * 50)

# Convert Age to numeric
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

print("Data type after conversion:", df['Age'].dtype)
print("-" * 50)

# Missing values
print("Missing value:", df['Age'].isna().sum())
print("-" * 50)

# Duplicate values
print("Duplicated:", df['Age'].duplicated().sum())
print("-" * 50)

# Frequency
print("Count duplicated:")
print(df['Age'].value_counts())
print("-" * 50)

# Zero values
print("Zero value:", (df['Age'] == 0).sum())
print("-" * 50)

# Negative values
print("Negative:", (df['Age'] < 0).sum())
print("-" * 50)

# Minimum and maximum
print("Max age:", df['Age'].max())
print("Min age:", df['Age'].min())

Data type: int64
--------------------------------------------------
Data type after conversion: int64
--------------------------------------------------
Missing value: 0
--------------------------------------------------
Duplicated: 48768
--------------------------------------------------
Count duplicated:
Age
36    1348
35    1337
33    1335
23    1329
31    1325
      ...
88       6
85       5
87       3
89       2
86       1
Name: count, Length: 74, dtype: int64
--------------------------------------------------
Zero value: 0
--------------------------------------------------
Negative: 0
--------------------------------------------------
Max age: 90
Min age: 17

In [10]:
df.columns

Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education_Num',
       'Marital_Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital_Gain', 'Capital_Loss', 'Hours_Per_Week', 'Native_Country',
       'Income'],
      dtype='object')

In [11]:
df.rename(columns={"Workclass": "Work_class"},inplace=True)
df.head(2)

,Age,Work_class,Fnlwgt,Education,Education_Num,Marital_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_Per_Week,Native_Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,50K or Less
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,50K or Less

In [12]:
# check missing value
# check workclass columns
print("missing value:",df['Work_class'].isna().sum())
print("-"*50)

# check  data type
print("data type:",df['Work_class'].dtype)

#remove space
df['Work_class']=df['Work_class'].str.strip()
print(df['Work_class'])
print("-"*50)

#check unique value
print("unique:",df['Work_class'].unique())
print("-"*50)
print("value :",(df['Work_class'] == "?").sum())
print("-"*50)

# convert ? symbol into nan value
df['Work_class']=df['Work_class'].replace("?",np.nan)
print(df['Work_class'])
print("-"*50)

# after covert check missing value
print("missing value:",df['Work_class'].isna().sum())
print("-"*50)

# convert missing value into mode
df['Work_class']=df['Work_class'].fillna(df['Work_class'].mode()[0])
print("fill missing value:",df['Work_class'])
print("-"*50)

missing value: 0
--------------------------------------------------
data type: object
0               State-gov
1        Self-emp-not-inc
2                 Private
3                 Private
4                 Private
               ...
48837             Private
48838             Private
48839             Private
48840             Private
48841        Self-emp-inc
Name: Work_class, Length: 48842, dtype: object
--------------------------------------------------
unique: ['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked']
--------------------------------------------------
value : 0
--------------------------------------------------
0               State-gov
1        Self-emp-not-inc
2                 Private
3                 Private
4                 Private
               ...
48837             Private
48838             Private
48839             Private
48840             Private
48841        Self-emp-inc
Name: Work_class, Length: 48842, dtype: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
fill missing value: 0               State-gov
1        Self-emp-not-inc
2                 Private
3                 Private
4                 Private
               ...
48837             Private
48838             Private
48839             Private
48840             Private
48841        Self-emp-inc
Name: Work_class, Length: 48842, dtype: object
--------------------------------------------------

In [13]:
print("missing value:",df['Work_class'].isna().sum())
print("-"*50)

missing value: 0
--------------------------------------------------

In [14]:
df.columns

Index(['Age', 'Work_class', 'Fnlwgt', 'Education', 'Education_Num',
       'Marital_Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital_Gain', 'Capital_Loss', 'Hours_Per_Week', 'Native_Country',
       'Income'],
      dtype='object')

In [15]:
# Check Fnlwgt column

# Convert Fnlwgt to numeric
df['Fnlwgt'] = pd.to_numeric(df['Fnlwgt'], errors='coerce')

# Check data type
print("data type:", df['Fnlwgt'].dtype)
print("-" * 50)

# Check missing value
print("missing value:", df['Fnlwgt'].isna().sum())
print("-" * 50)

# Check zero value
print("zero value:", (df['Fnlwgt'] == 0).sum())
print("-" * 50)

# Check negative value
print("negative value:", (df['Fnlwgt'] < 0).sum())
print("-" * 50)

# Check maximum and minimum value
print("max value:", df['Fnlwgt'].max())
print("min value:", df['Fnlwgt'].min())
print("-" * 50)

# Check duplicated values
print("duplicated:", df['Fnlwgt'].duplicated().sum())
print("-" * 50)

# Check value counts
print("count duplicated:")
print(df['Fnlwgt'].value_counts())

data type: int64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
negative value: 0
--------------------------------------------------
max value: 1490400
min value: 12285
--------------------------------------------------
duplicated: 20319
--------------------------------------------------
count duplicated:
Fnlwgt
203488    21
120277    19
190290    19
125892    18
126569    18
          ..
286983     1
185942     1
234220     1
214706     1
350977     1
Name: count, Length: 28523, dtype: int64

In [16]:
# check Education columns

# check data type
print("data type:",df['Education'].dtype)
print("-"*50)

# check unique
print("unique:",df['Education'].unique())
print("-"*50)

# check missing value
print("missing value:",df['Education'].isna().sum())
print("-"*50)

data type: object
--------------------------------------------------
unique: ['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']
--------------------------------------------------
missing value: 0
--------------------------------------------------

In [17]:
print("data type:", df['Fnlwgt'].dtype)

print("-"*50)

print("missing value:", df['Fnlwgt'].isna().sum())

print("-"*50)

print("zero value:", (df['Fnlwgt'] == 0).sum())

print("-"*50)

print("negative value:", (df['Fnlwgt'] < 0).sum())

print("-"*50)

print("max value:", df['Fnlwgt'].max())

print("min value:", df['Fnlwgt'].min())

print("-"*50)

print("duplicated:", df['Fnlwgt'].duplicated().sum())

data type: int64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
negative value: 0
--------------------------------------------------
max value: 1490400
min value: 12285
--------------------------------------------------
duplicated: 20319

In [18]:
# check Marital_Status columns

# check data type
print("data type:",df['Marital_Status'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Marital_Status'].isna().sum())
print("-"*50)

# check unique
print("unique:",df['Marital_Status'].unique())

data type: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']

In [19]:
#check Occupation columns

# check data type
print("data type:",df['Occupation'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Occupation'].isna().sum())
print("-"*50)

#check unique value
print("unique:",df['Occupation'].unique())
print("unique ?:",(df['Occupation'] == "?").sum())
print("-"*50)

# convert symbol into nan value
df['Occupation']=df['Occupation'].replace("?",np.nan)
print("nan:",df['Occupation'])

# fill them into using fillna
df['Occupation']=df['Occupation'].fillna(df['Occupation'].mode()[0])
print("fill missing value:",df['Occupation'])
print("-"*50)

data type: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' 'Protective-serv'
 'Armed-Forces' 'Priv-house-serv']
unique ?: 0
--------------------------------------------------
nan: 0             Adm-clerical
1          Exec-managerial
2        Handlers-cleaners
3        Handlers-cleaners
4           Prof-specialty
               ...
48837       Prof-specialty
48838       Prof-specialty
48839       Prof-specialty
48840         Adm-clerical
48841      Exec-managerial
Name: Occupation, Length: 48842, dtype: object
fill missing value: 0             Adm-clerical
1          Exec-managerial
2        Handlers-cleaners
3        Handlers-cleaners
4           Prof-specialty
               ...
48837       Prof-specialty
48838       Prof-specialty
48839       Prof-specialty
48840         Adm-clerical
48841      Exec-managerial
Name: Occupation, Length: 48842, dtype: object
--------------------------------------------------

In [20]:
# check Relationship columns

# check data type
print("data type:",df['Relationship'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Relationship'].isna().sum())
print("-"*50)

#check unique value
print("unique:",df['Relationship'].unique())

data type: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['Not-in-family' 'Husband' 'Wife' 'Own-child' 'Unmarried' 'Other-relative']

In [21]:
df.columns

Index(['Age', 'Work_class', 'Fnlwgt', 'Education', 'Education_Num',
       'Marital_Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital_Gain', 'Capital_Loss', 'Hours_Per_Week', 'Native_Country',
       'Income'],
      dtype='object')

In [22]:
#check Race colummns

#check data type
print("data type:",df['Race'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Race'].isna().sum())
print("-"*50)

#check unique value
print("unique:",df['Race'].unique())

data type: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['White' 'Black' 'Asian-Pac-Islander' 'Amer-Indian-Eskimo' 'Other']

In [23]:
#check Sex columns

# check data type
print("data type:",df['Sex'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Sex'].isna().sum())
print("-"*50)

#check unique
print("unique:",df['Sex'].unique())

data type: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['Male' 'Female']

In [24]:
# check Capital_Gain columns

# check data type
print("data type:",df['Capital_Gain'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Capital_Gain'].isna().sum())
print("-"*50)

#check zero value
print("zero  value:",(df['Capital_Gain'] == 0).sum())

data type: int64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero  value: 44807

In [25]:
# Check Capital_Loss column

# Convert to numeric
df['Capital_Loss'] = pd.to_numeric(df['Capital_Loss'], errors='coerce')

# Check data type
print("data type:", df['Capital_Loss'].dtype)
print("-"*50)

# Check missing value
print("missing value:", df['Capital_Loss'].isna().sum())
print("-"*50)

# Check zero value
print("zero value:", (df['Capital_Loss'] == 0).sum())
print("-"*50)

# Check negative value
print("negative value:", (df['Capital_Loss'] < 0).sum())
print("-"*50)

# Check maximum and minimum
print("max value:", df['Capital_Loss'].max())
print("min value:", df['Capital_Loss'].min())
print("-"*50)

# Check duplicated values
print("duplicated:", df['Capital_Loss'].duplicated().sum())

data type: int64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 46560
--------------------------------------------------
negative value: 0
--------------------------------------------------
max value: 4356
min value: 0
--------------------------------------------------
duplicated: 48743

In [26]:
# Check Hours_Per_Week column

# Convert to numeric
df['Hours_Per_Week'] = pd.to_numeric(
    df['Hours_Per_Week'],
    errors='coerce'
)

# Check data type
print("data type:", df['Hours_Per_Week'].dtype)
print("-"*50)

# Check missing value
print("missing value:", df['Hours_Per_Week'].isna().sum())
print("-"*50)

# Check zero value
print("zero value:", (df['Hours_Per_Week'] == 0).sum())
print("-"*50)

# Check negative value
print("negative value:", (df['Hours_Per_Week'] < 0).sum())
print("-"*50)

# Check unique value
print("unique:", df['Hours_Per_Week'].unique())

data type: int64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
negative value: 0
--------------------------------------------------
unique: [40 13 16 45 50 80 30 35 60 20 52 44 15 25 38 43 55 48 58 32 70  2 22 56
 41 28 36 24 46 42 12 65  1 10 34 75 98 33 54  8  6 64 19 18 72  5  9 47
 37 21 26 14  4 59  7 99 53 39 62 57 78 90 66 11 49 84  3 17 68 27 85 31
 51 77 63 23 87 88 73 89 97 94 29 96 67 82 86 91 81 76 92 61 74 95 79 69]

In [27]:
# check Native_Country columns

#check data type 
print("data type :",df['Native_Country'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Native_Country'].isna().sum())
print("-"*50)

# check unique value
print("unique:",df['Native_Country'].unique())
print("-"*50)

# convert symbol nito nan 
df['Native_Country']=df['Native_Country'].replace("?",np.nan)
print("unique ?:",df['Native_Country'])

#fill nan value 
df['Native_Country']=df['Native_Country'].fillna(df['Native_Country'].mode()[0])
print(df['Native_Country'])

data type : object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['United-States' 'Cuba' 'Jamaica' 'India' 'Mexico' 'South' 'Puerto-Rico'
 'Honduras' 'England' 'Canada' 'Germany' 'Iran' 'Philippines' 'Italy'
 'Poland' 'Columbia' 'Cambodia' 'Thailand' 'Ecuador' 'Laos' 'Taiwan'
 'Haiti' 'Portugal' 'Dominican-Republic' 'El-Salvador' 'France'
 'Guatemala' 'China' 'Japan' 'Yugoslavia' 'Peru'
 'Outlying-US(Guam-USVI-etc)' 'Scotland' 'Trinadad&Tobago' 'Greece'
 'Nicaragua' 'Vietnam' 'Hong' 'Ireland' 'Hungary' 'Holand-Netherlands']
--------------------------------------------------
unique ?: 0        United-States
1        United-States
2        United-States
3        United-States
4                 Cuba
             ...
48837    United-States
48838    United-States
48839    United-States
48840    United-States
48841    United-States
Name: Native_Country, Length: 48842, dtype: object
0        United-States
1        United-States
2        United-States
3        United-States
4                 Cuba
             ...
48837    United-States
48838    United-States
48839    United-States
48840    United-States
48841    United-States
Name: Native_Country, Length: 48842, dtype: object

In [28]:
# check Income column

# check data type
print("data type:", df['Income'].dtype)
print("-"*50)

# remove "." from Income values
df['Income'] = df['Income'].str.replace('.', '', regex=False)

# check missing value
print("missing value:", df['Income'].isna().sum())
print("-"*50)

# check unique value
print("unique:", df['Income'].unique())
print("-"*50)

# check frequency
print("value counts:")
print(df['Income'].value_counts())

data type: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
unique: ['50K or Less' 'Above 50K']
--------------------------------------------------
value counts:
Income
50K or Less    37155
Above 50K      11687
Name: count, dtype: int64

In [29]:
# replace symbol 
df['Income'] = df['Income'].replace({
    '<=50K': '50K or Less',
    '>50K': 'Above 50K'
})
print(df['Income'])

0        50K or Less
1        50K or Less
2        50K or Less
3        50K or Less
4        50K or Less
            ...
48837    50K or Less
48838    50K or Less
48839    50K or Less
48840    50K or Less
48841      Above 50K
Name: Income, Length: 48842, dtype: object

In [30]:
df.head(5)

,Age,Work_class,Fnlwgt,Education,Education_Num,Marital_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_Per_Week,Native_Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,50K or Less
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,50K or Less
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,50K or Less
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,50K or Less
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,50K or Less

In [31]:
df.to_csv("clean_income_data.csv",index=False)